Stock Market Predictor Preprocessing

In [1]:
import pandas as pd
import os

In [ ]:
# Define the folder containing the CSV files
folder_path = r"C:\Project\Python Datasets\Stock-Market-Predictor\data"

# Get all CSV files in the folder
csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]

for file in csv_files:
    # Read the CSV file
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path)
    
    # Get the Ticker name from cell B2 (row index 1, column index 1)
    ticker_name = df.iloc[0, 1]  # Adjust index to your data structure
    
    # Add the Ticker column and populate it with the ticker name
    df['Ticker'] = ticker_name

    # Rename the 'Price' column to 'Date'
    df.rename(columns={'Price': 'Date'}, inplace=True)

    # Convert the 'Date' column to datetime format
    df['Date'] = pd.to_datetime(df['Date'][2:])  # Assuming dates start from row 3

    # Define the date range
    start_date = '2020-01-01'
    end_date = '2025-01-22'

    # Filter rows based on the date range
    df = df[(df['Date'] >= start_date) & (df['Date'] <= end_date)]

    # Reorder columns to make 'Ticker' the first column
    columns = ['Ticker'] + [col for col in df.columns if col != 'Ticker']
    df = df[columns]

    # Save the updated file (overwrite or create a new one)
    updated_file_path = os.path.join(folder_path, f"updated_{file}")
    df.to_csv(updated_file_path, index=False)
    
    print(f"Updated {file} with Ticker: {ticker_name}")

Updated ADANIENT.csv with Ticker: ADANIENT.NS
Updated ADANIPORTS.csv with Ticker: ADANIPORTS.NS
Updated APOLLOHOSP.csv with Ticker: APOLLOHOSP.NS
Updated ASIANPAINT.csv with Ticker: ASIANPAINT.NS
Updated AXISBANK.csv with Ticker: AXISBANK.NS
Updated BAJAJ-AUTO.csv with Ticker: BAJAJ-AUTO.NS
Updated BAJAJFINSV.csv with Ticker: BAJAJFINSV.NS
Updated BAJFINANCE.csv with Ticker: BAJFINANCE.NS
Updated BHARTIARTL.csv with Ticker: BHARTIARTL.NS
Updated BPCL.csv with Ticker: BPCL.NS
Updated BRITANNIA.csv with Ticker: BRITANNIA.NS
Updated CIPLA.csv with Ticker: CIPLA.NS
Updated COALINDIA.csv with Ticker: COALINDIA.NS
Updated DIVISLAB.csv with Ticker: DIVISLAB.NS
Updated DRREDDY.csv with Ticker: DRREDDY.NS
Updated EICHERMOT.csv with Ticker: EICHERMOT.NS
Updated GRASIM.csv with Ticker: GRASIM.NS
Updated HCLTECH.csv with Ticker: HCLTECH.NS
Updated HDFCBANK.csv with Ticker: HDFCBANK.NS
Updated HDFCLIFE.csv with Ticker: HDFCLIFE.NS
Updated HEROMOTOCO.csv with Ticker: HEROMOTOCO.NS
Updated HINDALCO.csv with Ticker: HINDALCO.NS
Updated HINDUNILVR.csv with Ticker: HINDUNILVR.NS
Updated ICICIBANK.csv with Ticker: ICICIBANK.NS
Updated INDUSINDBK.csv with Ticker: INDUSINDBK.NS
Updated INFY.csv with Ticker: INFY.NS
Updated ITC.csv with Ticker: ITC.NS
Updated JSWSTEEL.csv with Ticker: JSWSTEEL.NS
Updated KOTAKBANK.csv with Ticker: KOTAKBANK.NS
Updated LT.csv with Ticker: LT.NS
Updated LTIM.csv with Ticker: LTIM.NS
Updated MARUTI.csv with Ticker: MARUTI.NS
Updated MM.csv with Ticker: M&M.NS
Updated NESTLEIND.csv with Ticker: NESTLEIND.NS
Updated NTPC.csv with Ticker: NTPC.NS
Updated ONGC.csv with Ticker: ONGC.NS
Updated POWERGRID.csv with Ticker: POWERGRID.NS
Updated RELIANCE.csv with Ticker: RELIANCE.NS
Updated SBILIFE.csv with Ticker: SBILIFE.NS
Updated SBIN.csv with Ticker: SBIN.NS
Updated SUNPHARMA.csv with Ticker: SUNPHARMA.NS
Updated TATACONSUM.csv with Ticker: TATACONSUM.NS
Updated TATAMOTORS.csv with Ticker: TATAMOTORS.NS
Updated TATASTEEL.csv with Ticker: TATASTEEL.NS
Updated TCS.csv with Ticker: TCS.NS
Updated TECHM.csv with Ticker: TECHM.NS
Updated TITAN.csv with Ticker: TITAN.NS
Updated ULTRACEMCO.csv with Ticker: ULTRACEMCO.NS
Updated UPL.csv with Ticker: UPL.NS
Updated WIPRO.csv with Ticker: WIPRO.NS

In [25]:
df = pd.read_csv(r"C:\Project\Python Datasets\Stock-Market-Predictor\data\updated_ADANIENT.csv")
df.head()

,Ticker,Date,Close,High,Low,Open,Volume
0,ADANIENT.NS,2020-01-01,205.827087,208.401774,204.638754,206.965889,1553127
1,ADANIENT.NS,2020-01-02,209.144501,211.125036,205.480514,205.975648,2991937
2,ADANIENT.NS,2020-01-03,206.272736,210.283322,203.797067,208.203754,2512421
3,ADANIENT.NS,2020-01-06,197.607880,205.728070,195.825395,205.728070,4353179
4,ADANIENT.NS,2020-01-07,202.064072,203.698007,198.598136,198.598136,2966120

In [26]:
df.describe()

             Close         High          Low         Open        Volume
count  1254.000000  1254.000000  1254.000000  1254.000000  1.254000e+03
mean   1912.658361  1948.254223  1878.889736  1916.266933  4.343667e+06
std    1117.990140  1134.434388  1103.972475  1122.020219  5.151532e+06
min     120.599144   129.476984   116.110331   119.822356  2.482490e+05
25%    1103.808838  1120.654411  1036.426880  1078.808758  1.516014e+06
50%    1986.736694  2068.829452  1906.323456  2006.682661  2.660114e+06
75%    2904.683899  2975.512573  2851.175259  2924.907883  4.991681e+06
max    4159.459961  4184.125438  4060.698718  4169.146469  4.926454e+07

In [30]:
df.isna().sum()

Ticker    0
Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64